---
- hosts: all
  become: True
  become_user: root
  tasks:
    - name: Update the repository cache and update package "nginx" to latest version
      ansible.builtin.apt:
        name: nginx
        state: latest
    - name: Enable service httpd, and not touch the state
      ansible.builtin.service:
        name: nginx
        enabled: yes
        state: started
